include:
  - ".xml"
  - ".txt"
  - ".html"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

title: "S.B. Poems - Poetry by Sidhi Batra"
description: "A collection of beautiful poems by Sidhi Batra"
url: "https://sidhibatra.github.io"
baseurl: "/S.B.-poems"
